// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: plugin/plugin.proto

package plugin

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *Input) Validate() error {
	if oneOfNester, ok := this.GetData().(*Input_Settings); ok {
		if oneOfNester.Settings != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(oneOfNester.Settings); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Settings", err)
			}
		}
	}
	if oneOfNester, ok := this.GetData().(*Input_Image); ok {
		if oneOfNester.Image != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(oneOfNester.Image); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Image", err)
			}
		}
	}
	return nil
}
func (this *Settings) Validate() error {
	return nil
}
func (this *Image) Validate() error {
	return nil
}
func (this *Output) Validate() error {
	if oneOfNester, ok := this.GetData().(*Output_Event); ok {
		if oneOfNester.Event != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(oneOfNester.Event); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Event", err)
			}
		}
	}
	if oneOfNester, ok := this.GetData().(*Output_Image); ok {
		if oneOfNester.Image != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(oneOfNester.Image); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Image", err)
			}
		}
	}
	return nil
}
func (this *Event) Validate() error {
	return nil
}
